concurrent = 10
check_interval = 60

[session_server]
  session_timeout = 1800

[[runners]]
  name = "runner 1"
  url = "https://gitlab.com"
  token = "<PASTE REGISTRATION TOKEN HERE>"
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "runner 2"
  url = "https://gitlab.com/"
  token = "<PASTE REGISTRATION TOKEN HERE>"
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
